### ISSUE TITLE
Cannot edit navigation after creating an item and assigning a related entity

### ISSUE THREAD

**Issue by stay2be** [VirtusLab/strapi-plugin-navigation#25]
First, let me thank you for this great plugin for strapi. Building navigations is easy and intuitive thanks to this custom UI.

Unfortunatly, I have the following problem: After creating a navigation item in the plugin UI and assigning a related entity ("page" collection type in this case), I cannot edit the navigation afterwards (after saving).

I get the following error:
<img width="839" alt="Screenshot 2021-01-10 at 23 01 26" src="https://user-images.githubusercontent.com/13693611/104136774-88315180-5398-11eb-92a8-a8f85956465c.png">
<img width="446" alt="Screenshot 2021-01-10 at 23 01 50" src="https://user-images.githubusercontent.com/13693611/104136778-8c5d6f00-5398-11eb-9654-e93380aed5e6.png">

Here is the configuration for the collection type, as mentioned in the plugin docs:
```json
{
  "kind": "collectionType",
  "collectionName": "pages",
  ...
  "attributes": {
    ...
    "navigation": {
      "model": "navigationitem",
      "plugin": "navigation",
      "via": "related",
      "configurable": false,
      "hidden": true
    }
    ...
  }
}
```

When I try to edit the `Navigationitem` item in the strapi UI, I get the following error:

<img width="553" alt="Screenshot 2021-01-10 at 23 02 11" src="https://user-images.githubusercontent.com/13693611/104136856-17d70000-5399-11eb-89c9-6c1a70ba462b.png">

And when I try to extend the "page" collection type in the Content-Types Builder, I get the following error:

`{"error":{"contentType.attributes.navigation.nature":["must be one of the following values: oneWay, manyWay, oneToOne, oneToMany, manyToOne, manyToMany"]}}`

I've tried it with different collection types, but no luck. I'm a little bit lost now and would appreciate any help.

- Strapi version: v3.4.1 (community edition)
- Node version: v14.15.4
- Database provider: PostgreSQL

**Comment by cyp3rius** [comment]
@stay2be as I see you've created additional navigation (apart of the main, created by default) for supporting footer. it seems that's the case of error as we didn't consider to support multiple navigations for beta version. Looking to manage it for official public release.

Let us check for when we will be able to deliver that.

**Comment by cyp3rius** [comment]
@stay2be the cause of the error for multiple navigations has been fixed. Anyway we're not recommend to use it until providing official support :) Ofc you can use it by your own risk.

**Comment by stay2be** [comment]
@cyp3rius Thanks for providing a new beta version. I've tried it with the new version, but still no luck. I have also deleted the second navigation, so only one is present at the time. I've recorded the following video the share the experience with the errors described in my initial post.


https://user-images.githubusercontent.com/13693611/104193352-4f3cbf80-5420-11eb-9c4c-9a7fdf4e4869.mp4

**Comment by cyp3rius** [comment]
@stay2be can I ask for providing the json response you received for this navigation GET `navigation/1` endpoint I think. Will try to imitate it on my end as checked for fresh version works well.

**Comment by stay2be** [comment]
@cyp3rius here's the reponse:

```json
GET http://localhost:1337/navigation/1

{
   "id":1,
   "name":"Main navigation",
   "slug":"main-navigation",
   "visible":true,
   "items":[
      {
         "id":1,
         "title":"Startseite",
         "type":"INTERNAL",
         "path":"INDEX",
         "externalPath":null,
         "uiRouterKey":"startseite",
         "menuAttached":false,
         "order":1,
         "parent":null,
         "master":1,
         "created_by":null,
         "updated_by":null,
         "created_at":"2021-01-11T14:39:44.133Z",
         "updated_at":"2021-01-11T14:39:44.476Z",
         "related":[
            {
               "__contentType":"Page",
               "id":1,
               "name":"Startseite",
               "meta_page_title":null,
               "meta_page_description":null,
               "bottom_info_text":"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ",
               "published_at":"2020-12-16T15:51:31.153Z",
               "created_by":1,
               "updated_by":1,
               "created_at":"2020-12-16T15:51:28.360Z",
               "updated_at":"2021-01-11T12:13:41.821Z"
            }
         ],
         "audience":[
            
         ],
         "items":[
            
         ]
      }
   ]
}
```

I tried to debug into your plugin so I have added some `console.log` but this error seems to come from Strapi itself. I have checked the model configuration on my side, but it matches your integration docs (and also the model docs from strapi regarding relations). Installing a fresh verion in node_modules makes no difference.

**Comment by cyp3rius** [comment]
Looks good, strange thing is happening to this content type. Can I ask you to check if Strapi didn't provide you an extensions to the plugin ? Sometimes it happen, that while doing some changes via Content Builder, Strapi adds overwrites so even after installing a plugin again changed are not taking any effect. 

Additional check: yarn.lock version of a package

**Comment by stay2be** [comment]
Ok, I've wiped my database and had strapi recreate the whole db and now it works. Maybe the schema had errors or was malformed while integrating the plugin. I've tested it with a fresh new strapi install and everything works now.

The other thing i noticed is that you cannot use the Content-Type Builder when the navigation attribute was set on a collection type. While this is not a showstopper, it could be addressed for the 1.0 release.

**Comment by cyp3rius** [comment]
Thanks for confirmation @stay2be .

Unfortunately the [Polymorhic relations](https://strapi.io/documentation/developer-docs/latest/concepts/models.html#relations) are not well supported by Strapi Content Builder. They will probably provide it in later releases.
