### ISSUE TITLE
[strapi-plugin-navigation] - Internal Server Error

### ISSUE THREAD

**Issue by danestves** [VirtusLab/strapi-plugin-navigation#35]
Hi! I'm using Strapi with MongoDB and when i want to save the menu gives me this error:

![image](https://user-images.githubusercontent.com/31737273/108723493-b3ac6d80-74fa-11eb-846c-4bfa2df4c479.png)

**Comment by danestves** [comment]
And in the console this:

![image](https://user-images.githubusercontent.com/31737273/108723576-cd4db500-74fa-11eb-9fe8-8783c9e402f9.png)

**Comment by cyp3rius** [comment]
@danestves version `1.0.0-beta.14 ` has been just released. Issue should be solved.

Confirm and close please.

**Comment by danestves** [comment]
![image](https://user-images.githubusercontent.com/31737273/108874228-5683eb00-75d2-11eb-975b-239ab6599fee.png)

For me the error still persist, i already rebuild all the UI and have a `custom.js` with this:

```js
module.exports = {
  plugins: {
    navigation: {
      additionalFields: ["audience"],
      excludedContentTypes: ["plugins::", "strapi"],
      allowedLevels: 2,
      contentTypesNameFields: {
        blogs: ["seo_title"],
        pages: ["title"],
      },
    },
  },
};

```

**Comment by cyp3rius** [comment]
@danestves as we've tested this code on the MondoDB and woks as expected I'm assuming that your case might be connected with some missing configuration. Will you be able to provide please your `Page` content type json?

**Comment by danestves** [comment]
```json
{
  "kind": "collectionType",
  "collectionName": "pages",
  "info": {
    "name": "Pages",
    "displayName": "Pages",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true,
    "previewable": true
  },
  "attributes": {
    "title": {
      "type": "string",
      "required": true
    },
    "slug": {
      "type": "uid",
      "targetField": "title",
      "required": false
    },
    "seo_description": {
      "type": "text",
      "required": true
    },
    "social_image": {
      "model": "file",
      "via": "related",
      "allowedTypes": ["images"],
      "plugin": "upload",
      "required": false
    },
    "sections": {
      "type": "dynamiczone",
      "components": [
        "sections.banner",
        "sections.features",
        "sections.image-text-call",
        "sections.price-table",
        "sections.divider",
        "sections.floating-box",
        "sections.slideshow",
        "sections.richtext",
        "sections.team",
        "sections.contact",
        "sections.map",
        "sections.seeed-hero",
        "sections.project-slider",
        "sections.blog"
      ]
    },
    "navigation": {
      "model": "navigationitem",
      "plugin": "navigation",
      "via": "related",
      "configurable": false,
      "hidden": true
    }
  }
}
```

BTW, i'm using Strapi 3.5.1

**Comment by cyp3rius** [comment]
Thanks @danestves I will test it against your content type and try to reproduce the issue.

To be sure, you don't have nothing defined in the `extensions/navigation`?

**Comment by danestves** [comment]
No @cyp3rius i don't have nothing in `extensions/navigations`

**Comment by cyp3rius** [comment]
Perfect, so trying to reproduce and found the cause.

**Comment by danestves** [comment]
Hi! How it's going the fix? Sorry for ask to much, it's because we are building a CMS and this feature will be very useful

**Comment by cyp3rius** [comment]
Most of the work is already done on a branch `fix/uid-instead-of-collection-name`. Couple minor fixes and set of tests remains, as refactor of a whole associations mechanism has changed to be env agnostic.

**Comment by cyp3rius** [comment]
Ticket auto closed because of fix merge and release `1.0.0-beta.16`. Hope it fixes all the issues @danestves. I was working directly on your content type and official mongoDB docker.

Just let me know if works, in case of on-going issue re-open please.

**Comment by danestves** [comment]
Finally it's working as expected to create the menu!
